### ISSUE TITLE
Support empty prefix for [http.services.ocmd]

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#1964]
When I edit revad.toml from:
```toml
[http.services.ocmd]
prefix = "ocm"
```
To:
```toml
[http.services.ocmd]
prefix = "bla"
```
Then:
* http://revad:19001/ocm/ocm-provider/ changes from a 200 to a 401
* http://revad:19001/bla/ocm-provider/ changes from a 401 to a 200

But when I change it to `prefix = ""` that does not have the desired effect of turning http://revad:19001/ocm-provider/ from a 401 to a 200.

There is probably an if-statement somewhere that makes this config var default to 'ocm' if it's falsy, or something like that.

Investigating.
